name: Flutter Test

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2.4.0

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: stable

    - name: Run Flutter Tests
      run: flutter test
